version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo No Configurations required

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install assembly:single

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/PicToPage-1.0-jar-with-dependencies.jar